[phases.setup]
nixPkgs = ['...', 'nodejs-20_x', 'cairo', 'pango', 'libpng', 'libjpeg', 'giflib', 'librsvg', 'pixman', 'pkg-config', 'python3']
aptPkgs = ['build-essential', 'libcairo2-dev', 'libpango1.0-dev', 'libjpeg-dev', 'libgif-dev', 'librsvg2-dev', 'libpixman-1-dev']

[phases.install]
dependsOn = ['setup']
cmds = ['rm -rf node_modules', 'npm ci --omit=dev']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/bin/chromium-browser'