[phases.setup]
nixPkgs = ['...', 'cairo', 'pango', 'libpng', 'libjpeg', 'giflib', 'librsvg', 'pixman', 'pkg-config', 'python3']
aptPkgs = ['build-essential', 'libcairo2-dev', 'libpango1.0-dev', 'libjpeg-dev', 'libgif-dev', 'librsvg2-dev', 'libpixman-1-dev']

[phases.install]
cmds = ['npm ci']

[start]
cmd = 'npm start'